image: maven:3.3.9

pipelines:
  branches:
    master:
      - step:
          name: Test
          script:
            - mvn clean test
      - step:
          name: Build
          script:
            - mvn clean install