version: '2.1'
services:
    backend_engine:
        build:
          context: .
        depends_on:
          db_engine:
            condition: service_healthy
        ports:
         - "8080:8080"
    db_engine:
        image: postgres
        environment:
          - POSTGRES_USER=daimler
          - POSTGRES_PASSWORD=daimler
        ports:
          - "5432:5432"
        healthcheck:
          test: ["CMD-SHELL", "pg_isready -U daimler"]
          interval: 10s
          timeout: 5s
          retries: 10